### ISSUE TITLE
You know you can install Nova with composer too?

### ISSUE THREAD

**Issue by tristanbailey** [swisnl/laravel-nova-mirror#3]
Hi

You know you can install Nova with Composer too?

`This repository was created because Nova only supplies a download which you need to copy to your project. This feels way too old-school and makes updating a bit hard. `

If you add an auth.json file in root of site, but not in git commit for security. 

In CI:
echo $NOVA_SECRET_JSON > auth.json

I think this is useful if you are keeping multiple ci or dev in sync and for a "server down" outage though.

**Comment by bbrala** [comment]
Yeah i saw that a while back. I should mention it in the README.

**Comment by JaZo** [comment]
@tristanbailey thanks for mentioning, we've added a note to the README!
