### ISSUE TITLE
i got problem

### ISSUE THREAD

**Issue by bsormagec** [swisnl/laravel-nova-mirror#4]
hello friend i got problem after 2.0.2 and its not running did you fix it ?

**Comment by JaZo** [comment]
Hi @bsormagec, we do not have a 2.x release. Perhaps you mean Laravel Nova 2.0.2? This repository is only a mirroring tool. Laravel Nova issues can be reported at https://github.com/laravel/nova-issues. If you are having issues with this tool, please create a new issue and follow the issue template.

**Comment by bsormagec** [comment]
No no you understand me wrong, I cant use this tool now its giving me error since last week do you have same error ?

**Comment by JaZo** [comment]
Please create a new issue and follow the issue template.
